apiVersion: ingress.baiding.tech/v1beta1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app-sample
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder
  name: app-sample
spec:
  # TODO(user): Add fields here
  image: nginx:latest
  replicas: 3
  enable_ingress: false #会被修改为true
  enable_service: true  #成功
